import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load Ancient Medium font and make it available as a CSS variable & class
const ancientMedium = localFont({
  src: "./fonts/Ancient-Medium.ttf",
  variable: "--font-ancient-medium",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Unconfessional",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply both the variable (for CSS usage) and the direct font class (ensures visibility)
        className={`${ancientMedium.variable} ${ancientMedium.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
